<?php
echo "<h2>welcome to php</h2>";
#echo "<br>";
#echo "<script>alert('studying php')</script>"
echo "<p style ='color: red; font-size: 40px;'>studying php</p>";
echo 10;
echo "<br>";
$fname = "Jerome";
echo "My name is " . $fname . " ,what about you?";
echo "<br>";
$lname = "Michael";
echo "My name is " . $fname . " but my surname is " . $lname;
echo "<br>";
$a = 6;
$b = 3;
$c = 7.5;
$d = 4;
echo "The sum of the three numbers is " . $a + $b + $c;
echo "<br>";
echo "The difference between the two numbers is " . $c - $b;
echo "<br>";
echo "The product of the three numbers is " . $a * $b * $c;
echo "<br>";
echo "The division of a from c is " . $c / $a;
echo "<br>";
echo "The mod of the two numbers is " . $a % $d;
echo "<br>";
$a += 4;
echo "The sum of the two numbers is " . $a;
echo "<br>";
$b -= 2;
echo "The difference between the two numbers is " . $b;
echo "<br>";
$c *= 3;
echo "The product of the two numbers is " . $c;
echo "<br>";
$d /= 3;
echo "The division of three from d is " . $d;
echo "<br>";
$p = pi();
echo "The value of pi is " . $p;
echo "<br>";
$w = pow(2,6);
echo "Two to the power of six is " . $w;
echo "<br>";
$s = sqrt(9);
echo "The square root of nine is " . $s;
echo "<br>";
$ce = 45;
$fa = ($ce * (9 / 5)) + 32;
echo "45 degrees Celcius is " . $fa . " degrees Fahrenheit";
echo "<br>";
$Fa = 45;
$Ce = ($Fa - 32) * (5 / 9);
echo "45 degrees Fahrenheit is " . $Ce . " degrees Celcius";
echo "<br>";
?>